adx_append: true
adx_appendto: true
adx_create: false
adx_delete: false
adx_entitylogicalname: p3i_product
adx_entityname: Product
adx_entitypermission_webrole:
- 4b63568b-2617-ed11-b83e-000d3aaaf9f7
- 4c63568b-2617-ed11-b83e-000d3aaaf9f7
adx_entitypermissionid: c0f94563-f025-ed11-b83d-00224882bcc4
adx_read: true
adx_scope: 756150000
adx_write: false
